apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dr0247nd4-dotnet-basic
  janus-idp.io/tekton: dr0247nd4-dotnet-basic
  backstage.io/kubernetes-id: dr0247nd4-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dr0247nd4-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
