apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dr0247nd4-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dr0247nd4-dotnet-basic-gitops